### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by MrMallenby** [ravmustang/AltisLife-eXpandedHousing#1]
Does this sync to the Database if so how do i add the needed column

**Comment by ravmustang** [comment]
No need to modify your database. When 5.0 is released a better setup and walk through install instructions for current missions will be done

**Comment by MrMallenby** [comment]
Could you tell me either way? im running 5.0.0 now and would love to get this running on my server

**Comment by ravmustang** [comment]
Alright, you are running the master branch from github and Altis RPG Life does not acknowledge the 5.0 as I encountered in their discord, they felt heavy sarcasm and wit was necessary....
If you are running this master branch and are this interested in running this addon, please consider working with me to get it done on your server. 
I will at the same time create the proper installation readme.md like I have for my wasteland version of the vector build system found here:
https://github.com/ravmustang/ArmA3_Wasteland_VectorBldg.Altis

ts3.eXpoch.INFO
or 
https://discord.me/eXpoch

**Comment by MrHeavyMetal** [comment]
i looked through the files and it seems the only thing needing changed is the altislife.sql to include the needed database column

**Comment by ravmustang** [comment]
Misinformation posts get deleted, issue closed as was answered in the first reply.
The second reply has the next steps for you to take.
